name: TapToTalker
options:
  bundleIdPrefix: com.devcalapps
  deploymentTarget:
    iOS: "17.0"
settings:
  TARGETED_DEVICE_FAMILY: "2"
targets:
  TapToTalker:
    type: application
    platform: iOS
    sources: [TapToTalker]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.devcalapps.TapToTalker
      DEVELOPMENT_TEAM: Y65K339Z7J
      INFOPLIST_KEY_UIStatusBarHidden: YES
      INFOPLIST_KEY_UILaunchScreen_Generation: NO
      INFOPLIST_KEY_UIApplicationSceneManifest_Generation: NO
      INFOPLIST_KEY_UIApplicationSupportsMultipleScenes: NO
      INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
      INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
  TapToTalkerTests:
    type: bundle.unit-test
    platform: iOS
    sources: [TapToTalkerTests]
    dependencies:
      - target: TapToTalker
